# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  # Change bridge to the name of your interface 
  # This is setup for a Macbook
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "Predictor"
    vb.cpus = 4
  end
  config.vm.provision "shell", path: "provision-app.sh"
end
